"""empty message

Revision ID: 960b9b722c8b
Revises: c47482a083ca
Create Date: 2024-05-16 16:16:37.361092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '960b9b722c8b'
down_revision = 'c47482a083ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_planet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planet_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['planet_id'], ['planet.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorite_character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_column('planet')
        batch_op.drop_column('faction')

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.drop_column('faction')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('faction', sa.VARCHAR(length=120), autoincrement=False, nullable=True))

    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('faction', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('planet', sa.VARCHAR(length=120), autoincrement=False, nullable=False))

    op.drop_table('favorite_character')
    op.drop_table('favorite_planet')
    # ### end Alembic commands ###
