"""empty message

Revision ID: c47482a083ca
Revises: 79db14307267
Create Date: 2024-05-07 20:33:38.553632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c47482a083ca'
down_revision = '79db14307267'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('faction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('faction_name', sa.String(length=120), nullable=False))
        batch_op.create_unique_constraint(None, ['faction_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('faction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('faction_name')

    # ### end Alembic commands ###
